export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const SEARCH_STUDENTS = 'SEARCH_STUDENTS';